name: Build LaTex summary

on: [pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build latex pdfs
        uses: docker://texlive/texlive:latest
        with:
          args: latexmk -pdf -cd -interaction=nonstopmode -file-line-error -jobname=analysis_III_full -outdir=../build ./src/main.tex
      - name: change flags
        run: sed 's/^.\{1\}//g' -i src/flags.tex
      - name: build without examples
        uses: docker://texlive/texlive:latest
        with:
          args: latexmk -pdf -cd -interaction=nonstopmode -file-line-error -jobname=analysis_III -outdir=../build ./src/main.tex
      - name: reset flags
        run: sed 's/^/%/' -i src/flags.tex
