name: Build LaTex summary

on: [pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build latex pdfs
        uses: docker://texlive/texlive:latest
        with:
          args: latexmk -pdf -cd -interaction=nonstopmode -file-line-error -jobname=analysis_III_full -outdir=../build ./src/main.tex
      - name: change flags
        run: sed 's/^.\{1\}//g' -i src/headers/flags.tex
      - name: build without examples
        uses: docker://texlive/texlive:latest
        with:
          args: latexmk -pdf -cd -interaction=nonstopmode -file-line-error -jobname=analysis_III -outdir=../build ./src/main.tex
      - name: reset flags
        run: sed 's/^/%/' -i src/headers/flags.tex
      - name: Archive analysis_III_full.pdf as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-analysis_III_full
          path: build/analysis_III_full.pdf
          retention-days: 5
      - name: Archive analysis_III.pdf as artifacts
        uses: actions/upload-artifact@v3
        with:
            name: compiled-analysis_III
            path: build/analysis_III.pdf
            retention-days: 5
