name: Build and deploy LaTex summary to GitHub-Pages

on:
  push:
  pull_request:
    branches: 
      - main
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_deploy_latex:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build latex pdfs
        uses: docker://texlive/texlive:latest
        with:
          args: latexmk -pdf -cd -interaction=nonstopmode -file-line-error -jobname=full -outdir=../build ./src/main.tex
      - name: Copy output
        run: |
          cp ./build/full.pdf ./pages/analysis_3_full.pdf
      - name: Setup Pages
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3
      - name: Upload artifact
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v2
        with:
          path: './pages'
      - name: Deploy to GitHub Pages
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v2
